# Generated by Django 4.1.3 on 2022-12-20 18:52

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_options_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.get_file_path),
        ),
    ]
