# Generated by Django 4.1.3 on 2022-12-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_informationproduct_product_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
        migrations.AddField(
            model_name='informationproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
        ),
    ]
