# Generated by Django 4.1.3 on 2023-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_address_remove_order_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('discount_percent', models.SmallIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
