# Generated by Django 4.1.3 on 2023-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_title_discountcode_code_discountcode_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progrssing', 'جاری'), ('Delivered', 'تکمبل شده'), ('Returned', 'مرجوع شده')], default='In Progrssing', max_length=130),
        ),
    ]
