# Generated by Django 4.1.3 on 2023-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progrssing', 'جاری'), ('Delivered', 'تکمیل شده'), ('Returned', 'مرجوع شده')], default='In Progrssing', max_length=130),
        ),
    ]
